name: 'todo-issues'
description: 'Create and manage GitHub issues from TODO comments!'
author: 'Jared Barboza <codeimpossible@users.noreply.github.com>'
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  githubToken:
    required: false
    description: 'The github token.'
    default: ${{ github.token }}
  markers:
    required: false
    description: 'The types of comments to search for'
    default: |
      TODO
      FIXME: bug
      HACK
      BUG: bug
      OPTIMIZE
      NOTE
  files:
    required: true
    description: files to search
    default: '**'
runs:
  using: 'node20'
  main: 'dist/index.js'
