name: 'todo-issues'
description: 'Create and manage GitHub issues from TODO comments!'
author: 'Jared Barboza <codeimpossible@users.noreply.github.com>'
inputs:
  markers:
    required: false
    description: 'The types of coments to search for'
    default: |
      TODO
      FIXME: bug
      HACK
      BUG: bug
      OPTIMIZE
      NOTE
  files:
    required: true
    description: files to search
    default: '**'
runs:
  using: 'node20'
  main: 'lib/main.js'
