name: 'todo-issues'
description: 'Create and manage GitHub issues from TODO comments!'
author: 'Jared Barboza <codeimpossible@users.noreply.github.com>'
branding:
  icon: 'heart'
  color: 'red'
inputs:
  githubToken:
    required: true
    description: 'The github token. Normally this should be ${{ secrets.GITHUB_TOKEN }}'
  markers:
    required: false
    description: 'The types of coments to search for'
    default: |
      TODO
      FIXME: bug
      HACK
      BUG: bug
      OPTIMIZE
      NOTE
  files:
    required: true
    description: files to search
    default: '**'
runs:
  using: 'node20'
  main: 'dist/index.js'
