name: 'coverage'
on:
  pull_request:

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
